# Generated by Django 5.1.4 on 2024-12-21 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Matematika')),
                ('description', models.TextField(verbose_name='Ishonchli')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='10.10.2024')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='10.11.2024')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Laziz')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='yuq')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='15.10.2024')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.course', verbose_name='Matematika')),
            ],
        ),
    ]
